######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 1 19:33:55 2014
######################################################################

TEMPLATE = lib
TARGET = MD5
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += shared

# Input
HEADERS += HTTPDigest.h MD5.h
SOURCES += HTTPDigest.c MD5.c test.c
